Create Sequence if not exists user_account_seq start 1;


CREATE TABLE  IF NOT EXISTS USERACCOUNT  (
    USER_ID int not null primary key  DEFAULT nextval('user_account_seq'),
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255),
    ID_NUMBER VARCHAR(255),
    EMAIL VARCHAR(255),
    MOBILE VARCHAR,
    ADDRESS_LINE1 VARCHAR,
    ADDRESS_LINE2 VARCHAR,
    TOWN VARCHAR,
    POSTCODE VARCHAR,
    COUNTRY VARCHAR,
    PROFILE_PHOTO VARCHAR,
    ACTIVE boolean default false,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FARMPOST  (
    POST_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID int not null ,
    TITLE TEXT  null,
    DETAILS TEXT not null,
    PHOTO VARCHAR,
    LIKES_COUNT INT,
    DELETED boolean default false,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERACCOUNT(user_id)
);
